# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='logo/2w.png', upload_to='img')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageGet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bounds', models.CharField(max_length=512)),
                ('resource_id', models.CharField(max_length=512, null=True)),
                ('text', models.CharField(max_length=128, null=True)),
                ('x_class', models.CharField(max_length=128)),
                ('is_run_error', models.IntegerField(default=0)),
                ('operation', models.CharField(max_length=64, null=True)),
                ('link_node', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pageGet.PageGet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pjt_name', models.CharField(max_length=50)),
                ('app_file', models.FileField(upload_to='appfile')),
                ('app_plate', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('crom_status', models.IntegerField(default=0)),
                ('pjt_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.User')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pjt_id', models.IntegerField(default=0)),
                ('pjt_name', models.CharField(max_length=128, null=True)),
                ('page_info', models.CharField(max_length=4096, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('pjt_parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pageGet.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsePjt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('pjt_info', models.CharField(max_length=4096, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('user_parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userAuth.User')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseRpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pjt_id', models.IntegerField(default=0)),
                ('pjt_name', models.CharField(max_length=128, null=True)),
                ('rpt_info', models.CharField(max_length=4096, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('pjt_parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pageGet.Project')),
            ],
        ),
        migrations.AddField(
            model_name='objectimg',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageGet.PageGet'),
        ),
    ]
