# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageGet', '0003_auto_20180121_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsepage',
            old_name='create_time',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='responserpt',
            old_name='create_time',
            new_name='add_time',
        ),
        migrations.AddField(
            model_name='responsepage',
            name='mod_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='responserpt',
            name='mod_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
