# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageGet', '0004_auto_20180121_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsepjt',
            name='add_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='responsepjt',
            name='mod_time',
            field=models.DateTimeField(),
        ),
    ]
