# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pageGet', '0010_auto_20180121_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DurationField(default=django.utils.timezone.now),
        ),
    ]
