# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pageGet', '0012_auto_20180121_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DurationField(default=datetime.datetime(2018, 1, 21, 14, 35, 39, 119574, tzinfo=utc)),
        ),
    ]
